# Build docker image and run tests on a container based on created image
name: Build and test

on:
  push:
    paths-ignore:
      - 'docs/**'

  pull_request:
    paths-ignore:
      - 'docs/**'

  workflow_dispatch:

jobs:
  docker-build-test-autotest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Test version
        id: version
        run: |
          shell /usr/bin/env python3 src/codeplag/brand_consts.py --version

      - name: Get output_version
        run: |
          echo '${{ steps.version.outputs }}'
          exit 10

      - name: Build docker image
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "ACCESS_TOKEN = '${ACCESS_TOKEN}'" > .env
          make docker

      - name: Run tests in the docker container based on the created image
        run: |
          make docker-test

      - name: Run autotests in the docker container based on the created image
        run: |
          make docker-autotest
